options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };

    // MISKONFIGURASI SENGAJA UNTUK LAB:
    // Zone transfer (AXFR) dibuka untuk siapa saja, bukan cuma secondary DNS
    // resmi. Ini adalah salah satu temuan yang diharapkan pada fase DNS
    // enumeration. Jangan tiru di server produksi nyata.
    allow-transfer { any; };
};

zone "corplab.local" {
    type master;
    file "/etc/bind/zones/db.corplab.local";
    allow-transfer { any; };
};
