# Virtual host tambahan - hanya bisa diakses dengan Host header yang benar.
# Peserta akan menemukan nama-nama subdomain ini lewat DNS zone transfer
# (BIND allow-transfer misconfig) dan/atau SAN sertifikat TLS di corplab.local.
# Setelah ditemukan, tambahkan ke /etc/hosts -> 127.0.0.1 <subdomain> untuk mengaksesnya.

server {
    listen 80;
    listen 443 ssl;
    server_name admin.corplab.local;

    ssl_certificate     /etc/nginx/certs/corplab.crt;
    ssl_certificate_key /etc/nginx/certs/corplab.key;

    root /usr/share/nginx/vhosts/admin;
    index index.html;
    add_header X-Powered-By "NusaCMS/2.3.1" always;
}

server {
    listen 80;
    listen 443 ssl;
    server_name dev.corplab.local;

    ssl_certificate     /etc/nginx/certs/corplab.crt;
    ssl_certificate_key /etc/nginx/certs/corplab.key;

    root /usr/share/nginx/vhosts/dev;
    index index.html;
    add_header X-Powered-By "NusaCMS/2.4.0-dev" always;
    add_header X-Debug-Mode "true" always;
    add_header X-Flag "NUSA{h34d3r_b0c0rk4n_l1ngkung4n}" always;
}

server {
    listen 80;
    listen 443 ssl;
    server_name staging.corplab.local;

    ssl_certificate     /etc/nginx/certs/corplab.crt;
    ssl_certificate_key /etc/nginx/certs/corplab.key;

    root /usr/share/nginx/vhosts/staging;
    index index.html;
    add_header X-Powered-By "NusaCMS/2.4.0-beta" always;
}

server {
    listen 80;
    listen 443 ssl;
    server_name api.corplab.local;

    ssl_certificate     /etc/nginx/certs/corplab.crt;
    ssl_certificate_key /etc/nginx/certs/corplab.key;

    root /usr/share/nginx/vhosts/api;
    index index.html;
    add_header X-Powered-By "NusaCMS/2.3.1" always;
}

server {
    listen 80;
    listen 443 ssl;
    server_name git.corplab.local;

    ssl_certificate     /etc/nginx/certs/corplab.crt;
    ssl_certificate_key /etc/nginx/certs/corplab.key;

    # Sengaja diarahkan ke docroot yang sama dengan situs utama
    # (termasuk .git yang ke-expose) - subdomain ini "seharusnya" untuk
    # internal git server, tapi salah konfigurasi jadi alias situs utama.
    root /usr/share/nginx/html;
    index index.html;
}
